### ISSUE TITLE
EVAL MODE = TRUE Disables UI 

### ISSUE THREAD

**Issue by Sayeedbetgeri** [openflagr/flagr#459]
https://github.com/checkr/flagr/blob/d4b7b279061d85b740cd52aaf7379180272adaca/pkg/config/env.go#L44

EVALONLYMODE Disables UI access we cannot even see the enabled/diabled flagKeys
Any alternative on UI to at least fetch read only values to know what flag keys we have on UI.

**Comment by zhouzhuojie** [comment]
There're two reasons UI is not enabled for `FLAGR_EVAL_ONLY_MODE`

- UI talks the `crud` API set, which is not enabled because FLAGR_EVAL_ONLY_MODE can only read from the in-memory cache, and doesn't support any changes to the data source
- FLAGR_EVAL_ONLY_MODE will derive the source of truth from either `json_file` or `json_http`, and we can assume that those files are created from a normal flagr deployment or source-code controlled place.
