### ISSUE TITLE
Calls to Flagr:: EvaluationApi#post_evaluation with an empty body take an inordinate time to resolve

### ISSUE THREAD

**Issue by derrelldurrett** [openflagr/flagr#526]
Calls to Flagr:: EvaluationApi#post_evaluation with an empty body take an inordinate time to resolve. Typically, in our systems, calls to that method with any body content are returned within < 1 ms, whereas calls with an empty body require up to 60 ms to process. The post_evaluation method should return instantly if the body is empty, as if the body was not provided.

## Expected Behavior
When called with an empty body, `flagr` should respond immediately, and as it does today with a missing body.

## Current Behavior
When called with an empty body (length `0`), `flagr` takes an excessive amount of time to return (over 60 times the amount of time it takes with a body that has length greater than `0`.

## Possible Solution
Return immediately, treating it as a missing body.

## Steps to Reproduce (for bugs)
Call `/flagr/api/v1/evaluation` with an empty body.

## Context
This causes false errors in our system in which we think the system is slow to respond to a client, when in fact the client is providing an invalid request.

## Your Environment
* Version used (`rbflagr-1.1.12`):
* Server type and version: 5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 x86_64 GNU/Linux
* Operating System and version (`uname -a`): 5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 x86_64 GNU/Linux
* Link to your project: (private repo)

**Comment by Gerst20051** [comment]
I'm very curious about what this issue might be.

It could be in the `rbflagr` library rather than in `flagr` itself.

https://github.com/openflagr/rbflagr

https://github.com/openflagr/rbflagr/blob/1fc16ee47e02bcc4dc01a9304a24a54442f0a8d8/lib/rbflagr/api/evaluation_api.rb#L33-L71

https://github.com/openflagr/rbflagr/blob/1fc16ee47e02bcc4dc01a9304a24a54442f0a8d8/lib/rbflagr/api_client.rb#L349

Direct curls to the flagr api return immediately for both of the following scenarios.

`[$]> curl -X "POST" "https://flagr.host.net/api/v1/evaluation"`

```json
{
  "code": 602,
  "message": "body in body is required"
}
```

`[$]> curl -X "POST" "https://flagr.host.net/api/v1/evaluation" -H 'Content-Type: application/json; charset=utf-8' -d $'{}'`

```json
{
  "evalContext": {},
  "evalDebugLog": {
    "msg": "flagID 0 not found or deleted",
    "segmentDebugLogs": null
  },
  "timestamp": "2023-01-20T21:59:29Z"
}
```
